FROM node:alpine

COPY repo /app/site/
COPY config.js /app/site/websocket/config.js
COPY local_settings.py /app/site/dmoj/local_settings.py

WORKDIR /app/
RUN npm install qu ws simplesets

EXPOSE 15100
EXPOSE 15101
EXPOSE 15102

ENTRYPOINT node /app/site/websocket/daemon.js
